services:
  # 企业微信集成平台应用
  wework-platform:
    image: wework-platform:v1.0.0
    ports:
      - "9002:9002"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://wework:wework123@mysql:3306/wework_db
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - wework-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/api/connections"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    security_opt:
      - no-new-privileges:true

  # MySQL 数据库
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=wework_db
      - MYSQL_USER=wework
      - MYSQL_PASSWORD=wework123
      - MYSQL_ROOT_HOST=%
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - wework-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "wework", "-pwework123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Redis 缓存
  redis:
    image: redis:7-alpine
    platform: linux/amd64
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - wework-network
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Adminer 数据库管理工具
  adminer:
    image: adminer
    platform: linux/amd64
    ports:
      - "8080:8080"
    networks:
      - wework-network
    restart: unless-stopped
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  wework-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 